directionality: rtl
theme_advanced_toolbar_location: top

theme_advanced_toolbar_align: right
theme_advanced_statusbar_location: 
theme_advanced_buttons1:
  - fullscreen
  - image
  - link
  - numlist
  - underline
  - italic
  - bold
theme_advanced_buttons2:
theme_advanced_buttons3:
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
force_br_newlines: true
force_p_newlines: false
forced_root_block: ''